# .github/workflows/firebase-deploy.yml (최종 수정)

name: Deploy to Firebase (Hosting + Functions)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create firebase-config.js from secrets
        run: |
          mkdir -p public
          cat > public/firebase-config.js <<EOF
          window.__FBCONFIG__ = {
            apiKey: "${{ secrets.FB_API_KEY }}",
            authDomain: "${{ secrets.FB_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FB_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FB_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FB_APP_ID }}"
          };
          EOF

      - name: Validate Firebase secrets (fail if any is missing)
        run: |
          check() { [ -n "$1" ] || { echo "::error::Missing secret $2"; exit 1; }; }
          check "${{ secrets.FB_API_KEY }}" FB_API_KEY
          check "${{ secrets.FB_AUTH_DOMAIN }}" FB_AUTH_DOMAIN
          check "${{ secrets.FB_PROJECT_ID }}" FB_PROJECT_ID
          check "${{ secrets.FB_STORAGE_BUCKET }}" FB_STORAGE_BUCKET
          check "${{ secrets.FB_MESSAGING_SENDER_ID }}" FB_MESSAGING_SENDER_ID
          check "${{ secrets.FB_APP_ID }}" FB_APP_ID
          check "${{ secrets.GCP_SA_KEY }}" GCP_SA_KEY
          check "${{ secrets.FIREBASE_PROJECT_ID }}" FIREBASE_PROJECT_ID


      - name: Install Functions deps
        run: |
          if [ -d "functions" ]; then
            cd functions && npm install
          else
            echo "functions directory not found, skipping npm install."
          fi

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 수정된 부분: functions 폴더 유무에 따라 다른 배포 명령을 실행합니다.
      - name: Deploy to Firebase
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          if [ -d "functions" ]; then
            firebase deploy --only hosting,functions --project "$FIREBASE_PROJECT_ID" --force
          else
            firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --force
          fi
